/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-15-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Arthimaticcalculations {
    public void addition(integer x, integer y){
        Integer z = x + y;
        System.debug(z);
    }
    public void Subtraction(integer x, integer y){
        Integer z = x - y;
        System.debug(z);
    }
    public void Multiplication(integer x, integer y, integer m){
        Integer z = x * y * m;
        System.debug(z);
    }
}
