/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-31-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
///this home address
public class arthcalc {
    public Integer addition(integer x, integer y){
        Integer z = x + y;
        return z;
    }
    public Integer addition(integer x,integer y,integer z ,integer m){
        Integer sumvalue = x + y + z + m;
        return sumvalue;
    }
}
