/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-15-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Calculator2 {
    public String printAndReturnMessage(String msg){
        String r=msg + '...OK Cool';
        return r;
    }
public Integer add (Integer num1, Integer num2){
    Integer sum=num1+num2;
    return sum;
    }    
public Integer add(Integer num1, Integer num2, Integer num3){
    Integer sum=num1+num2+num3;
    return sum;
    }       
}
