/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-14-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class calculator {
    public void printNewMessage(String msg){
        System.debug(msg);
    }
public void add (integer a, integer b){
    Integer sum= a + b;
    system.debug(sum);
}    
}
