public  class checkDatatypes {
    public void MethodBoolean(){
        Boolean checkBoolean=false;
        System.debug(checkBoolean);
    }
    public void MethodInteger(){
        Integer varFirst=1;
        Integer varSecond=2;
        system.debug(varFirst+' and '+varSecond);
    }
    public void Stringmethod(){
        String varName='Name';
        String var2Name='Farhat';
        System.debug(varName+':'+var2Name);
    }
}
