/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-21-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class ListDemo {
   public static void candidateList(){
    List<String> listCandidate=new List<String>();
    listCandidate.add('Mergen');
    listCandidate.add('Ashyr');
    listCandidate.add('Vitap');
   }
   public static void randomIntegerList() {
    List<Integer> listInteger=new List<Integer>();
    listInteger.add(7);
    listInteger.add(9);
    listInteger.add(15);
   }
}
