/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-11-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class PrimitiveDataTypeDemo2 {
    public void print1(){
        Id id1='0018Z00002f7UvZQAU';
        System.debug('print id '+id);
        Object obj1='this is a string';
        Object obj2=45;
        Object obj3=true;
        System.debug(obj1+' '+obj2+' '+obj3);
    }
}
