/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-18-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class rankHandler {
    public String rankPrize(Integer rank){
        String prize = '';
        if(rank == 1){
            prize='Gold';
        }else if(rank == 2){
            prize='Silver';
        }





        return prize;
    }
}
