/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-21-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class candidates {
    public String name;
    public String gender;
    public static String companyName;
    public void printCandidate(){
        System.debug('Name is '+name+', ('+gender +')');
        System.debug('Company Name= '+companyName);
    }
    sta
}

