/**
 * @description       : 
 * @author            : ChangeMeIn@UserSettingsUnder.SFDoc
 * @group             : 
 * @last modified on  : 07-12-2022
 * @last modified by  : ChangeMeIn@UserSettingsUnder.SFDoc
**/
public class Primitivedata_Assignment {
   public void primitiveDataAssignmentMethod(){
    Id id1='0018Z00002f7UvZQAU';
    String string1='the following Id belongs to Accouts';
    Boolean boolean1=true;
    System.debug('The ID is '+id1+'. The String is '+string1+'. The Boolean is '+boolean1+'.');
   }
}
